### ISSUE TITLE
Allow using variables in includes

### ISSUE THREAD

**Issue by afm-sayem** [raml-org/raml-spec#533] opened 2016-07-17 01:32 UTC
> Parameters cannot be used within an !include tag specification of the include file location.

IMO this restriction severely limits how resourceTypes can be used. Since we can not use variables in specifying a location, we have to explicitly define the whole structure again in order to load a file somewhere in the nested structure. Which makes defining the structure in a resourceType a bit pointless.

For example I have:

api.raml
```raml
resourceTypes:
  - collection: !include resourceTypes/collection.raml
/roles:
  type: { collection: { resourceName: roles } }
/users
  type: { collection: { resourceName: users } }
```

resourceTypes/collection.raml
```raml
get:
  description: Get all <<resourceName>>, optionally filtered
  responses:
    200:
      body:
        application/json:
          schema: <<resourceName>>
          example: !include examples/<<resourceName>>.json
```
The last line results into an error.

I have to define the whole structure in my `api.raml` file again to load the example from external files. Any reason why raml 0.8 can not be augmented to use variables in `!include` path? Is there any workaround to this situation?

**Comment by ymek** [comment] 2016-08-01 21:54
This is a duplicate of #84. 

Current Status:
_"We will not add support for this feature immediately in v1.0! Don't panic, it's just for this version ;)"_

**Comment by sichvoge** [comment] 2016-08-02 10:09
Thanks @ymek. I will close this issue.

**Closed by sichvoge** 2016-08-02 10:09 UTC
Labels: duplicate
